[project]
name = "hireforge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
    "langgraph>=0.6.2",
    "notebook>=7.4.4",
    "pdfplumber>=0.11.7",
    "python-dotenv>=1.1.1",
]
